version: "2"
services:
  leader-test:
    image: leader_test
    entrypoint: "/usr/local/bin/run.sh"
    command: ['--tcp', '5678']
    networks:
      - default
    expose:
      - 5678
networks:
  default:
    external:
      name: consulsandbox_default
